#!/bin/bash

# Start in root always
if [[ $(basename `pwd`) == docker ]]
then
    cd ../
fi

docker ps -a | grep yt8m -q
if [ $? -eq 0 ]; then
    docker rm -f yt8m
fi

port="8888"
while true;
do
    echo "Trying port = $port"
    netstat -ntpl 2> /dev/null | grep $port -q 
    if [ $? -eq 1 ]; then
        docker run --name yt8m -d -v $PWD:/home -p $port:8888 
                               -v /tmp/.X11-unix:/tmp/.X11-unix \
                               -e DISPLAY=$DISPLAY-p 6006:6006 yt8m
        echo "Using port $port"
        break
    else
        ((port--))
    fi
done
